name: Secret scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
name: Secret scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: |
          python -m pip install --upgrade pip
          pip install detect-secrets

      - name: Run detect-secrets scan
        run: |
          # run a full-scan across the repository and write JSON output
          python -m detect_secrets scan --all-files --output-file detect-secrets-output.json || true
          if [ -s detect-secrets-output.json ]; then
            echo "detect-secrets found potential secrets"
            cat detect-secrets-output.json
            # fail the job to block PRs with findings
            exit 2
          else
            echo "no secrets found"
          fi

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: detect-secrets-output
          path: detect-secrets-output.json


